Feat: Updated jmeter job executor example for Keptn 0.12.x-0.13.x
keptn-contrib/artifacthub pull request #112
Opened 2022-03-29 15:02 UTC by TannerGilbert

2022-03-31 17:50 UTC, TannerGilbert commented
Works on both my local k3s setup and on my GKE cluster.

![image](https://user-images.githubusercontent.com/36239763/161118453-5d018980-8256-41d7-aef6-2dcff0d87197.png)

2022-04-01 07:20 UTC, christian-kreuzberger-dtx commented on jmeter/0.2.0/README.md
> +The following configuration will allow you to run the `basiccheck.jmx` (e.g., from the [Keptn Carts example](https://github.com/keptn/examples/tree/master/onboarding-carts/jmeter)) using the Job-Exec
here we refer to `basiccheck.jmx`, in the example below it's `load.jmx` though.

2022-04-01 07:21 UTC, christian-kreuzberger-dtx commented on jmeter/0.2.0/README.md
> +keptn add-resource --project=sockshop --service=carts --stage=staging --resource=jmeter.yaml --resourceUri=job/config.yaml
we never explicitly mentioned that the file above is called `jmeter.yaml`, can you just add a quick info before the code above?

2022-04-01 07:21 UTC, christian-kreuzberger-dtx commented on jmeter/0.2.0/README.md
> +
Please mention here that the file that follows below is called `jmeter.yaml`

2022-04-01 07:22 UTC, christian-kreuzberger-dtx commented on jmeter/0.2.0/README.md
> +Now the Job-Executor service will execute the JMeter tests whenever you trigger a new evaluation.
Replace "you trigger a new evaluation." with "you trigger a delivery, e.g., `keptn trigger delivery --project sockshop --service carts --image ...`"

2022-04-01 07:22 UTC, christian-kreuzberger-dtx requested changes
Thanks for the update! left some comments

2022-04-04 10:29 UTC, christian-kreuzberger-dtx approved these changes
LGTM

2022-04-04 10:29 UTC, merged