Added `PagerDuty` service on keptn artifacthub
keptn-contrib/artifacthub pull request #185
Opened 2022-09-30 18:46 UTC by afzal442

This PR supports `PagerDuty` integration with `keptn` webhook
Closes: https://github.com/keptn/integrations/issues/18

cc @agardnerIT

2022-09-30 18:47 UTC, afzal442 commented
cc @grabnerandi @oleg-nenashev @robertjahn @christian-kreuzberger-dtx

2022-09-30 21:22 UTC, oleg-nenashev commented on pagerduty/1.0.0/README.md
> +TODO
```suggestion

```

2022-10-12 13:05 UTC, StackScribe commented on pagerduty/1.0.0/README.md
> +The [keptn webhook service](https://github.com/keptn/keptn/tree/master/webhook-service), which comes "out of the box" with Keptn, will be used to listen for Keptn events and trigger webhooks into Pag
```suggestion
The [keptn webhook service](https://github.com/keptn/keptn/tree/master/webhook-service) and documented on the [Webhook Integration](https://keptn.sh/docs/0.19.x/integrations/webhooks/) page, which comes "out of the box" with Keptn, will be used to listen for Keptn events and trigger webhooks into PagerDuty. In this way new PagerDuty projects, tasks or anything else in PagerDuty are created in response to a [Keptn CloudEvent](https://keptn.sh/docs/0.19.x/reference/miscellaneous/events/)
```

2022-10-12 13:07 UTC, StackScribe commented on pagerduty/1.0.0/README.md
> +1. Navigate to a keptn project and to go the integrations screen
```suggestion
1. Navigate to a Keptn project and to go the integrations screen
```

2022-10-12 13:08 UTC, StackScribe commented on pagerduty/1.0.0/README.md
> +That's it! Execute the sequence and an PagerDuty service task/incidentS will be automatically created.
```suggestion
That's it! Execute the sequence and PagerDuty service task/incidentS will be automatically created.
```

2022-10-14 06:29 UTC, afzal442 commented
It'll be great if it can be reviewed before KCD. 😄

2022-10-27 20:17 UTC, agardnerIT requested changes
`The keptn webhook service and documented` > `The keptn webhook service is documented`
`In this way new PagerDuty projects` > `In this way, new PagerDuty projects`
`response to a Keptn CloudEvent` > `response to a Keptn CloudEvent.`
`Navigate to our Sign Up page,...` > `[Sign up](https://www.pagerduty.com/sign-up/) for a PagerDuty account`

`This can be done programmatically` how? You don't tell me. Please tell me or (better) point me to docs that tell me.

`service task/incidentS` > `service tasks / incidents`

Please add `webhook` and `notification` as keywords to `artifacthub-pkg.yml`

2022-10-28 04:27 UTC, afzal442 commented
Thanks much @agardnerIT for your review and suggestions here. That really reminded me of @StackScribe who scooped up for any typos and all.

2022-10-28 18:29 UTC, afzal442 commented
Thanks @agardnerIT for heads up! I made it now. Have a look again.

2022-12-21 14:19 UTC, afzal442 commented
Heyya folks, can I get reviews on it again? I hope we can make it before this year ends, 😉 

cc @grabnerandi

2022-12-22 06:49 UTC, agardnerIT approved these changes
LGTM. Let's merge and make any new changes moving forwards. Sorry for the delay!

2022-12-22 06:49 UTC, merged