feat:Add shell script integration
keptn-contrib/artifacthub pull request #90
Opened 2022-02-24 07:35 UTC by agardnerIT

2022-03-02 22:47 UTC, oleg-nenashev requested changes
I would strongly suggest documenting security considerations for users of this integration here or on the Job executor service page. Having generic script support is awesome, but it becomes much more complicated when potential security exploits are considered (e.g. patching shipyard file in a pull request)

2022-03-02 22:48 UTC, oleg-nenashev commented
Also, "alpine" is probably a bad example for those who want to do scripting. Too many limitations in the image out of the box

2022-03-04 07:03 UTC, christian-kreuzberger-dtx approved these changes
LGTM

2022-03-04 07:10 UTC, christian-kreuzberger-dtx commented
@oleg-nenashev I think we can merge this for now. Explaination below.

ad *security considerations*: Job-executor-service with default settings is secure. The example above does not provide ways to threaten the cluster nor the user. On the contrary, Keptn's built-in helm-service is a huge security loop-hole as it allows deployment of any workload to any namespace on the Kubernetes cluster BY DEFAULT.

> Having generic script support is awesome, but it becomes much more complicated when potential security exploits are considered (e.g. patching shipyard file in a pull request)

No need to patch the shipyard-file, that's the beauty of Job-executor-service. The only thing you need to patch is job/config.yaml, and patching in that sense means using a newer Docker image.
Comparing with ANY OTHER Keptn integration, this is the best way of handling the security situation. All other Keptn services statically depend on a pre-defined alpine image with pre-defined dependencies, that are NOT updated. With job-executor, you have the chance to always have an up2date image.

> Also, "alpine" is probably a bad example for those who want to do scripting. Too many limitations in the image out of the box

Alpine is not the best example to get started, agreed. But it's also not a bad one. Alpine is small, not bloated with 100 tools, etc... You can always extend it - and it's one of the first choices when it comes to creating your own containers.
That being said, we can easily switch to `debian:11.2-slim` instead of `alpine`. For now, I think we can merge this, and adapt later.

2022-03-07 11:59 UTC, merged